{
 "title": "CPU and Memory Usage",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, exported_namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{exported_namespace=~\"$namespace\"}, exported_pod)"
   },
   {
    "name": "container",
    "query": "label_values(kube_pod_container_info{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"} , exported_container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster wide",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Total CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m]))",
     "legendFormat": "Total CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "Total CPU Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores)",
     "legendFormat": "Total CPU Limits"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\"})",
     "legendFormat": "Total Memory usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)",
     "legendFormat": "Total Memory Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes)",
     "legendFormat": "Total Memory Limits"
    }
   ]
  },
  {
   "title": "Total CPU Usage by Namespace",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage by Namespace",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Namespace wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total CPU Usage of namespace: $namespace",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_namespace=~\"$namespace\"})",
     "legendFormat": "CPU Requests "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=~\"$namespace\"})",
     "legendFormat": "CPU Limits "
    }
   ]
  },
  {
   "title": "Total Memory Usage of namespace: $namespace",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\", namespace=~\"$namespace\"})",
     "legendFormat": "Memory usage "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_namespace=~\"$namespace\"})",
     "legendFormat": "Memory Requests "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_namespace=~\"$namespace\"})",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "Total CPU Usage by Pods",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", namespace=~\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage by Pods",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Pod wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Total CPU Usage of $namespace/$pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"})",
     "legendFormat": "CPU Requests "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"})",
     "legendFormat": "CPU Limits "
    }
   ]
  },
  {
   "title": "Total Memory Usage of: $namespace/$pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Memory usage "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"})",
     "legendFormat": "Memory Requests "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\"})",
     "legendFormat": "Memory Limits "
    }
   ]
  },
  {
   "title": "Total CPU Usage by Containers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage by Containers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "container wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Total CPU Usage of $namespace/$pod/$container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m]))",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "CPU Requests "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "CPU Limits "
    }
   ]
  },
  {
   "title": "Total Memory Usage of: $namespace/$pod/$container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_namespace=~\"$namespace\", exported_pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Memory Limits"
    },
    {
     "expr": "sum(container_memory_rss{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_cache{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum(container_memory_swap{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Working set"
    }
   ]
  }
 ]
}